### ISSUE TITLE
Schema does not parse correctly for go structs that contain multiple nested values

### ISSUE THREAD

**Issue by nkarpenko** [spaceavocado/apidoc#3]
When generating the openapi.yaml schema for that contains a nested value, it works as expected and generates for correct yaml.

However, if the struct contains multiple nested values, for the first nested value it calculates it correctly. But for the 2nd+ nested values it has to calculate, it ends up including keys from the previous nested struct it just calculated. Sorry the explanation isn't great, but I included the use case example below.

e.g. below is an example of the nested go struct
```
// struct with nested values
type A struct {
  b B
  c C
}

type B struct {
  id int
  nameB string
}

type C struct {
  id int
  nameC string
}
```
e.g. below is the schema output I would expect
```
A:
  type: object
  properties:
    B:
      type: object
        properties:
          id: integer
          nameB: string
    C:
      type: object
        properties:
          id: integer
          nameC: string
```

e.g. below is the actual schema that gets outputted. 
```
A:
  type: object
  properties:
    B:
      type: object
        properties:
          id: integer
          nameB: string
    C:
      type: object
        properties:
          id: integer
          nameB: string
          id: integer
          nameC: string
```
